project:
  type: website
  output-dir: docs
website:
  title: "Alex Skeels"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - cv.qmd
      - software.qmd
      - posters.qmd
      - contact.qmd
format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

